# Generated by Django 2.2.28 on 2022-08-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rasgjkf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rasgjkf',
            name='yuirtr',
        ),
        migrations.AddField(
            model_name='rasgjkf',
            name='yuirtr12',
            field=models.TextField(blank=True),
        ),
    ]
