# Generated by Django 2.2.28 on 2022-08-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20220812_1034"),
    ]

    operations = [
        migrations.CreateModel(
            name="Abhjjjhg",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bfhdjdj", models.TextField()),
            ],
        ),
    ]
