# Generated by Django 2.2.28 on 2022-08-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_abhjjjhg"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Rasgjkf",
        ),
    ]
