# Generated by Django 2.2.28 on 2022-08-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_rasgjkf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devtest123',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
