# Generated by Django 2.2.28 on 2022-08-31 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_abhjiy231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devtest123',
            name='clas456',
        ),
    ]
